CPP 		= g++
CXXFLAGS	= -g -O3 -Wall -fPIC -D_REENTRANT -Wno-deprecated

ROOTCFLAGS	:= $(shell root-config --cflags)
ROOTLIBS     	:= $(shell root-config --libs)
ROOTGLIBS    	:= $(shell root-config --glibs)
CXXFLAGS	+= $(ROOTCFLAGS)

LIB = ../lib

LIBS 		= $(ROOTGLIBS) \
          -lm $(LIB)/INGRIDEVENTSUMMARY.so $(LIB)/IngridHitSummary.so \
          $(LIB)/IngridSimHitSummary.so $(LIB)/IngridSimVertexSummary.so \
          $(LIB)/IngridSimParticleSummary.so $(LIB)/BeamInfoSummary.so \
          $(LIB)/IngridBasicReconSummary.so $(LIB)/Ingrid1stReducSummary.so \
          $(LIB)/IngridTrackSummary.so $(LIB)/NeutInfoSummary.so \
          $(LIB)/PMReconSummary.so $(LIB)/PMAnaSummary.so \


SRC = ../src
INC = ../inc

CXXFLAGS += -I$(LIB) -I$(SRC) -I$(INC)

TARGET = IngTClster IngBasicRecon IngReconMuBasic IngGetOnlyBasic \
         IngGetOnlyBasicMC get_daily_evt get_daily_evt_corr \
         PMrecon IngAnaVertex PMAna PMGetOnlyBasic PMGetOnlyBasicMC \
         IngMergePM

all: $(TARGET)

IngTClster: IngTClster.o

IngBasicRecon: IngBasicRecon.o

IngReconMuBasic: IngReconMuBasic.o

IngGetOnlyBasic: IngGetOnlyBasic.o

IngGetOnlyBasicMC: IngGetOnlyBasicMC.o

get_daily_evt: get_daily_evt.o

get_daily_evt_corr: get_daily_evt_corr.o

IngMergePM: IngMergePM.o

PMrecon: PMrecon.o

IngAnaVertex: IngAnaVertex.o

PMAna: PMAna.o

PMGetOnlyBasic: PMGetOnlyBasic.o

PMGetOnlyBasicMC: PMGetOnlyBasicMC.o




%: %.o
	@echo "Now make $@"
	@$(CPP) -o $@ $< $(CXXFLAGS) $(LIBS)
	@echo "..Compile done! "

%.o: %.cc
	@echo "Start Compiling $<"
	@$(CPP) $(CXXFLAGS) -c $<
	@echo ".. Compiling Object Files $<   --> done"
	@echo ""

clean: 
	@echo "Now Clean Up"
	rm -f $(TARGET) *~ *.o *.o~ core
