CMT_tag=$(tag)
CMTROOT=/home/sorel/CMT/CMT/v1r18p20061003
CMT_root=/home/sorel/CMT/CMT/v1r18p20061003
CMTVERSION=v1r18p20061003
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/home/sorel/CMT/CMT/v1r18p20061003/${CMTBIN}:/usr/lib/news/bin:/usr/local/bin:/home/bquilain/bin:/cern/root/root.v5.20.00/bin:/export/scbn00/home/condor/condor-7.0.5/bin:/export/scbn00/home/condor/condor-7.0.5/sbin:/usr/lib64/qt-3.3/bin:/usr/kerberos/bin:/bin:/usr/bin
CLASSPATH=/home/sorel/CMT/CMT/v1r18p20061003/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=c++
cppflags=-g -pipe -O0 -Wall -ansi -Wctor-dtor-privacy -Wnon-virtual-dtor -fpic 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc52-gcc412
INGRID_tag=$(tag)
INGRIDROOT=/data/home/bquilain/Ingrid_Process/INGRID/v1r1
INGRID_root=/data/home/bquilain/Ingrid_Process/INGRID/v1r1
INGRIDVERSION=v1r1
INGRID_linkopts= -L$(INGRIDROOT)/$(INGRID_tag) -lonlineMonMain 
LD_LIBRARY_PATH=/data/home/bquilain/Ingrid_Process/INGRID/v1r1/Linux-x86_64:/cern/root/root.v5.20.00/lib:/home/sorel/Nuance/Nuance/v3/Linux-x86_64
tag=Linux-x86_64
package=INGRID
version=v1r1
PACKAGE_ROOT=$(INGRIDROOT)
srcdir=../src
bin=../$(INGRID_tag)/
javabin=../classes/
mgrdir=cmt
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin
use_linkopts= $(cmt_installarea_linkopts)   $(INGRID_linkopts) 
use_requirements=requirements $(CMTROOT)/mgr/requirements 
use_includes= 
use_fincludes= $(use_includes)
use_stamps= $(INGRID_stamps) 
use_cflags=  $(INGRID_cflags) 
use_pp_cflags=  $(INGRID_pp_cflags) 
use_cppflags=  $(INGRID_cppflags) 
use_pp_cppflags=  $(INGRID_pp_cppflags) 
use_fflags=  $(INGRID_fflags) 
use_pp_fflags=  $(INGRID_pp_fflags) 
includes= $(ppcmd)"$(srcdir)" $(use_includes)
fincludes= $(includes)
onlineMonMain_use_linkopts=  $(INGRID_linkopts) 
DSTMaker_use_linkopts=  $(INGRID_linkopts) 
Calc_MPPC_new_use_linkopts=  $(INGRID_linkopts) 
Calc_MPPC_new_ci_use_linkopts=  $(INGRID_linkopts) 
IngCalib_new_use_linkopts=  $(INGRID_linkopts) 
IngCalib_ADCNLCorrected_use_linkopts=  $(INGRID_linkopts) 
Calc_MPPC_new_ci_2_use_linkopts=  $(INGRID_linkopts) 
constituents= dictionary version register onlineMonMain DSTMaker Calc_MPPC_new Calc_MPPC_new_ci IngCalib_new IngCalib_ADCNLCorrected Calc_MPPC_new_ci_2 
all_constituents= $(constituents)
constituentsclean= Calc_MPPC_new_ci_2clean IngCalib_ADCNLCorrectedclean IngCalib_newclean Calc_MPPC_new_ciclean Calc_MPPC_newclean DSTMakerclean onlineMonMainclean registerclean versionclean dictionaryclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
documentation_constituents= doxygen 
documentation_constituentsclean= doxygenclean 
