#!/bin/bash +x
home/bquilain/CC0pi_XS/Reconstruction/app/PMreconRevOfficial -r 14000 -s 0 -f /export/scraid2/data/bquilain/MCfiles/PMMC_Run1_10_wNoise.root -o /export/scraid2/data/bquilain/MCfiles/PMMC_Run1_10_wNoise_recon_Systematics8_  2.root -e 8 -v   2
home/bquilain/CC0pi_XS/Reconstruction/app/PMAnaRevOfficial -r 14000 -s 0 -f /export/scraid2/data/bquilain/MCfiles/PMMC_Run1_10_wNoise_recon_Systematics8_  2.root -o /export/scraid2/data/bquilain/MCfiles/PMMC_Run1_10_wNoise_ana_Systematics8_  2.root
/home/bquilain/CC0pi_XS/Reconstruction/app/PMAnaRevOfficial -r 14000 -s 0 -f /export/scraid2/data/bquilain/MCfiles/PMMC_Run1_10_wNoise_recon_Systematics8_  2.root -o /export/scraid2/data/bquilain/MCfiles/PMMC_Run1_10_wNoise_ana_Systematics8_  2.root



